import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import Layout from '@/components/Layout'
import profilePic from '../../public/images/profile/developer-pic-1.png'
import AnimatedText from '@/components/AnimatedText'
import { motion } from 'framer-motion'

export default function Home() {
  return (
    <>
      <Head>
        <title>Bernard</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='flex items-center w-full min-h-full text-white'>
        <Layout className='pt-0'>
          <div className='w-full flex items-center justify-between'>
            <div className='w-1/2'>
              <Image src={profilePic} alt='profile' className='w-full h-auto' />
            </div>
            <div className='w-1/2 flex flex-col items-center self-center'>
              <AnimatedText text='Transforming Imagination into Reality with Code and Design.' className='!text-6xl !text-left' />
              <p>
              As a skilled full-stack developer, I am dedicated to turning ideas into innovative web applications. Explore my latest projects and articles, showcasing my expertise in web development. Let's bring digital vision to life through code!
              </p>
            </div>
          </div>
        </Layout>
      </main>
    </>
  )
}
